export as namespace R;
export * from "./src/$curried-functions";
export * from "./src/$placeholder";
export * from "./src/$types";
import * as __ from "./src/__";
import * as add from "./src/add";
import * as addIndex from "./src/addIndex";
import * as adjust from "./src/adjust";
import * as all from "./src/all";
import * as allPass from "./src/allPass";
import * as always from "./src/always";
import * as and from "./src/and";
import * as any from "./src/any";
import * as anyPass from "./src/anyPass";
import * as ap from "./src/ap";
import * as aperture from "./src/aperture";
import * as append from "./src/append";
import * as apply from "./src/apply";
import * as applySpec from "./src/applySpec";
import * as ascend from "./src/ascend";
import * as assoc from "./src/assoc";
import * as assocPath from "./src/assocPath";
import * as binary from "./src/binary";
import * as bind from "./src/bind";
import * as both from "./src/both";
import * as call from "./src/call";
import * as clamp from "./src/clamp";
import * as clone from "./src/clone";
import * as dec from "./src/dec";
import * as descend from "./src/descend";
import * as divide from "./src/divide";
import * as inc from "./src/inc";
import * as map from "./src/map";
import * as mathMod from "./src/mathMod";
import * as mean from "./src/mean";
import * as median from "./src/median";
import * as modulo from "./src/modulo";
import * as multiply from "./src/multiply";
import * as nAry from "./src/nAry";
import * as negate from "./src/negate";
import * as or from "./src/or";
import * as prepend from "./src/prepend";
import * as product from "./src/product";
import * as subtract from "./src/subtract";
import * as sum from "./src/sum";
import * as unary from "./src/unary";
export { __, add, addIndex, adjust, all, allPass, always, and, any, anyPass, ap, aperture, append, apply, applySpec, ascend, assoc, assocPath, binary, bind, both, call, clamp, clone, dec, descend, divide, inc, map, mathMod, mean, median, modulo, multiply, nAry, negate, or, prepend, product, subtract, sum, unary };
