export as namespace R;
export * from "./src/$curried-functions";
export * from "./src/$placeholder";
export * from "./src/$types";
import * as __ from "./src/__";
import * as add from "./src/add";
import * as addIndex from "./src/addIndex";
import * as adjust from "./src/adjust";
import * as all from "./src/all";
import * as allPass from "./src/allPass";
import * as any from "./src/any";
import * as anyPass from "./src/anyPass";
import * as map from "./src/map";
export { __, add, addIndex, adjust, all, allPass, any, anyPass, map };
