export const namespace = 'R';
export const tPlaceholder = 'Placeholder';
export const tPlaceholderAbbr = 'PH';
export const tCurriedFunction = (n: number) => `CurriedFunction${n}`;
export const tMorphism = 'Morphism';
export const tIndexedMorphism = 'IndexedMorphism';
export const tMapper = 'Mapper';
export const tListMapper = 'ListMapper';
export const tDictionaryMapper = 'DictionaryMapper';
export const tList = 'List';
export const tDictionary = 'Dictionary';
export const tPredicate = 'Predicate';
export const tMappable = 'Mappable';
